version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aegir
    versions:
    - 31.0.0
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
    - 33.1.0
    - 33.1.1
  - dependency-name: it-length-prefixed
    versions:
    - 4.0.0
    - 5.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: err-code
    versions:
    - 3.0.0
